baseurl = "https://norihitoishida.github.io/"
title = "Norihito Ishida's personal website"
theme = "hugo-coder"
languageCode = "jp"
publishDir = "docs"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Norihito Ishida"
    info = "Machine Learning Engineer"
    description = "Norihito Ishida's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"
    
    hideFooter = false
    hidecredits = false
    hidecopyright = false
    
    since = 2020
    
    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/norihitoishida/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/norihitoishida/"



# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = ""
    weight = 1
    url = "/about/"